description "BitcoinIII Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env BITCOINIIID_BIN="/usr/bin/bitcoinIIId"
env BITCOINIIID_USER="bitcoinIII"
env BITCOINIIID_GROUP="bitcoinIII"
env BITCOINIIID_PIDDIR="/var/run/bitcoinIIId"
# upstart can't handle variables constructed with other variables
env BITCOINIIID_PIDFILE="/var/run/bitcoinIIId/bitcoinIIId.pid"
env BITCOINIIID_CONFIGFILE="/etc/bitcoinIII/bitcoinIII.conf"
env BITCOINIIID_DATADIR="/var/lib/bitcoinIIId"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # bitcoinIIId will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$BITCOINIIID_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run bitcoinIIId."
        echo "The setting must appear in $BITCOINIIID_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"BitcoinIII Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$BITCOINIIID_PIDDIR"
    chmod 0755 "$BITCOINIIID_PIDDIR"
    chown $BITCOINIIID_USER:$BITCOINIIID_GROUP "$BITCOINIIID_PIDDIR"
    chown $BITCOINIIID_USER:$BITCOINIIID_GROUP "$BITCOINIIID_CONFIGFILE"
    chmod 0660 "$BITCOINIIID_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$BITCOINIIID_PIDFILE" \
    --chuid $BITCOINIIID_USER:$BITCOINIIID_GROUP \
    --exec "$BITCOINIIID_BIN" \
    -- \
    -pid="$BITCOINIIID_PIDFILE" \
    -conf="$BITCOINIIID_CONFIGFILE" \
    -datadir="$BITCOINIIID_DATADIR" \
    -disablewallet \
    -daemon

